### ISSUE TITLE
Issue with Maps not downloading.

### ISSUE THREAD

**Issue by benrobson** [chatasma/MapPuller#1]
Hey,
Thanks for making this plugin for TGM, was actually looking for something like this. I was sent this repo from the peeps at Warzone to use for my own Server.

- I've configured the auth_token correctly (although I am not so sure what permissions to give it, I assume just repo permissions?)
- Could there be a feature implemented instead of downloading certain maps, just download the entire repo instead of mapnames?

While attempting to get maps to download I got 2 errors:
```
[09:54:56 ERROR]: Error occurred while enabling MapPuller v1.0 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 1
        at me.tqnk.mp.util.MapScavenger.<init>(MapScavenger.java:28) ~[?:?]
        at me.tqnk.mp.MapPuller.createScavengerFromConfig(MapPuller.java:78) ~[?:?]
        at me.tqnk.mp.MapPuller.onEnable(MapPuller.java:63) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:932) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.Bukkit.reload(Bukkit.java:688) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-83]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-83]
        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-83]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-83]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-83]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-83]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

```
[09:55:01 WARN]: Exception in thread "Thread-42" java.lang.IllegalStateException: zip file closed
[09:55:01 WARN]:        at java.util.zip.ZipFile.ensureOpen(Unknown Source)
[09:55:01 WARN]:        at java.util.zip.ZipFile.getEntry(Unknown Source)
[09:55:01 WARN]:        at java.util.jar.JarFile.getEntry(Unknown Source)
[09:55:01 WARN]:        at java.util.jar.JarFile.getJarEntry(Unknown Source)
[09:55:01 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133)
[09:55:01 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216)
[09:55:01 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
[09:55:01 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[09:55:01 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[09:55:01 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[09:55:01 WARN]:        at org.apache.http.pool.AbstractConnPool.closeExpired(AbstractConnPool.java:558)
[09:55:01 WARN]:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.closeExpiredConnections(PoolingHttpClientConnectionManager.java:409)
[09:55:01 WARN]:        at me.tqnk.shade.unirest.http.utils.SyncIdleConnectionMonitorThread.run(SyncIdleConnectionMonitorThread.java:24)
```

Hope this helps!
:D

**Comment by BennyDoesTheStuff** [comment]
What does your config look like?

**Comment by benrobson** [comment]
> 
> 
> What does your config look like?

```
source:
  mapnames:
    - Aequabilis
    - Gobi
    - Hallows
  target: "Maps"
  repo: "crafting-for-christ/Maps"
  auth_token: "TOKEN"
```
The maps are only there for testing, a token is also there as well.

**Comment by chatasma** [comment]
Hey, I didn't have a proper example on how the `auth_token` should look like.

`auth_token` should look like `username:token`, i.e. `chatasma:TOKEN`

**Comment by benrobson** [comment]
> 
> 
> Hey, I didn't have a proper example on how the `auth_token` should look like.
> 
> `auth_token` should look like `username:token`, i.e. `chatasma:TOKEN`

Adding your example fixes the errors, but I can't see my /Maps directory updating.

**Comment by BennyDoesTheStuff** [comment]
A few things to note:

1. When putting in the map names, you can also put in the name of the folder. So for example, if you have a bunch of maps in a "CTW" folder, you can simply type CTW and it'll auto fetch and download all the maps in that folder.
2. To update the Maps repo, you would do /downloadmaps in-game. This will fetch the maps and update the Maps directory with everything you have on Github. I don't think this plugin currently supports auto downloading, so for now you'll just need to type /downloadmaps and then once it finishes just use /loadmaps in TGM to reload the maps repo.

**Comment by benrobson** [comment]
> 
> 
> A few things to note:
> 
>     1. When putting in the map names, you can also put in the name of the folder. So for example, if you have a bunch of maps in a "CTW" folder, you can simply type CTW and it'll auto fetch and download all the maps in that folder.
> 
>     2. To update the Maps repo, you would do /downloadmaps in-game. This will fetch the maps and update the Maps directory with everything you have on Github. I don't think this plugin currently supports auto downloading, so for now you'll just need to type /downloadmaps and then once it finishes just use /loadmaps in TGM to reload the maps repo.

So I've done 2 things, updated my config to map folders to the following:

> mapnames:
>     - Blitz
>     - CTW
>     - DTM
>     - DTW
>     - FFA
>     - Infection
>     - KOTH
>     - TDM

Restarting the server and running download maps now throws an error:

> [00:29:32 INFO]: shadowolfyt issued server command: /downloadmaps
> [00:29:33 WARN]: me.tqnk.shade.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
> [00:29:33 WARN]:        at me.tqnk.shade.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
> [00:29:33 WARN]:        at me.tqnk.shade.unirest.request.BaseRequest.asObject(BaseRequest.java:80)
> [00:29:33 WARN]:        at me.tqnk.mp.util.MapScavenger.getGithubContentFromUrl(MapScavenger.java:93)
> [00:29:33 WARN]:        at me.tqnk.mp.util.MapScavenger.loadMaps(MapScavenger.java:36)
> [00:29:33 WARN]:        at me.tqnk.mp.command.LoadCommand.lambda$onCommand$0(LoadCommand.java:31)
> [00:29:33 WARN]:        at java.lang.Thread.run(Unknown Source)
> [00:29:33 WARN]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
> [00:29:33 WARN]:        at me.tqnk.shade.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
> [00:29:33 WARN]:        at me.tqnk.shade.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
> [00:29:33 WARN]:        ... 5 more
> [00:29:33 WARN]: Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
> [00:29:33 WARN]:        at me.tqnk.mp.MapPuller$1.readValue(MapPuller.java:44)
> [00:29:33 WARN]:        at me.tqnk.shade.unirest.http.HttpResponse.<init>(HttpResponse.java:101)
> [00:29:33 WARN]:        ... 6 more
> [00:29:33 WARN]: Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
> [00:29:33 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:899)
> [00:29:33 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:852)
> [00:29:33 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:801)
> [00:29:33 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:773)
> [00:29:33 WARN]:        at me.tqnk.mp.MapPuller$1.readValue(MapPuller.java:42)
> [00:29:33 WARN]:        ... 7 more
> [00:29:33 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
> [00:29:33 WARN]:        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
> [00:29:33 WARN]:        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
> [00:29:33 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
> [00:29:33 WARN]:        ... 11 more
> [00:29:33 INFO]: Could not find repository from https://api.github.com/repos/crafting-for-christ/Maps/contents

**Comment by benrobson** [comment]
Hey,
Any update on this?

**Comment by chatasma** [comment]
Based on the stacktrace, it seems like the response it got from the GitHub API was not what it expected (it got an object instead of an array). One possibility is that the "Not Found" response is being sent which is an object

```json
{
"message": "Not Found",
"documentation_url": "https://docs.github.com/rest"
}
```

I'm not sure if that is the actual response being received in your scenario but it could be. Perhaps it could be due to a bad auth token?
